### PR TITLE
R tutor03 edits

### PR DESCRIPTION
**Pull request by rmcd1024**
Added a second challenge using 'c'.

### CODE REVIEW

**Comment by eddelbuettel** [comment]
Cool. A PR.  I wonder if there is a way to do better than to do commit 46 files -- maybe exclude the html and png files?

**Comment by rmcd1024** [comment]
Yes, I was thinking that we could ignore html for sure, and maybe md also.
I'm only editing Rmd. On the other hand, not a huge deal.

**Comment by eddelbuettel** [comment]
Not a huge deal, but if we ever wanted to contribute upstream at SWC we'd have to play [by their rules](https://github.com/swc-nw/r-novice-gapminder/blob/gh-pages/CONTRIBUTING.md) which contain

> When editing lessons, please only commit changes to the Markdown files, not the generated HTML. We will re-create the HTML after your pull request is merged. (Working this way ensures that each change only needs to be reviewed once, in one place.)

I'd be happy either way but I am not sure how to 'slice' a single commit or pull request containing 40+ files (such as this one) after the fact.   There may of course be way (this being git with the infinity of options).

**Comment by rmcd1024** [comment]
On Sun, Aug 9, 2015 at 4:49 PM, Dirk Eddelbuettel notifications@github.com
wrote:

> Not a huge deal, but if we ever wanted to contribute upstream at SWC we'd
> have to play by their rules
> https://github.com/swc-nw/r-novice-gapminder/blob/gh-pages/CONTRIBUTING.md
> which contain
> 
> When editing lessons, please only commit changes to the Markdown files,
> not the generated HTML. We will re-create the HTML after your pull request
> is merged. (Working this way ensures that each change only needs to be
> reviewed once, in one place.)
> 
> I'd be happy either way but I am not sure how to 'slice' a single commit
> or pull request containing 40+ files (such as this one) after the fact.
> There may of course be way (this being git with the infinity of options).
> 
> So I'm now faced with this issue because it seems I accidentally submitted
> my first pull request to swcarpentry. I wonder if I ended up on their page
> and not realized it wasn't ours!

Bob

**Comment by eddelbuettel** [comment]
Not what I said, or tried to say.

Your PR was to us, but comprised 46 files.

I am wondering if by accepting it here and now we close ourselves some doors -- over there.

**Comment by eddelbuettel** [comment]
Few things are easier than to just close or ignore a pull request.

**Comment by eddelbuettel** [comment]
I'll just nuke this one as it contains 46 files.

**Pull request closed without merging**
